// GENERATED CODE - DO NOT MODIFY BY HAND
part of 'country_localizations.dart';

mixin _$CountryLocalizations {
  static const _en = {
    'ad': 'Andorra',
    'ae': 'United Arab Emirates',
    'af': 'Afghanistan',
    'ag': 'Antigua and Barbuda',
    'al': 'Albania',
    'am': 'Armenia',
    'ao': 'Angola',
    'ar': 'Argentina',
    'at': 'Austria',
    'au': 'Australia',
    'az': 'Azerbaijan',
    'ba': 'Bosnia and Herzegovina',
    'bb': 'Barbados',
    'bd': 'Bangladesh',
    'be': 'Belgium',
    'bf': 'Burkina Faso',
    'bg': 'Bulgaria',
    'bh': 'Bahrain',
    'bi': 'Burundi',
    'bj': 'Benin',
    'bn': 'Brunei',
    'bo': 'Bolivia',
    'br': 'Brazil',
    'bs': 'The Bahamas',
    'bt': 'Bhutan',
    'bw': 'Botswana',
    'by': 'Belarus',
    'bz': 'Belize',
    'ca': 'Canada',
    'cd': 'Congo (Democratic Republic of)',
    'cf': 'Central African Republic',
    'cg': 'Congo (Republic of)',
    'ch': 'Switzerland',
    'ci': 'Ivory Coast',
    'cl': 'Chile',
    'cm': 'Cameroon',
    'cn': 'China',
    'co': 'Colombia',
    'cr': 'Costa Rica',
    'cu': 'Cuba',
    'cv': 'Cape Verde',
    'cy': 'Cyprus',
    'cz': 'Czech Republic',
    'de': 'Germany',
    'dj': 'Djibouti',
    'dk': 'Denmark',
    'dm': 'Dominica',
    'do': 'Dominican Republic',
    'dz': 'Algeria',
    'ec': 'Ecuador',
    'ee': 'Estonia',
    'eg': 'Egypt',
    'er': 'Eritrea',
    'es': 'Spain',
    'et': 'Ethiopia',
    'fi': 'Finland',
    'fj': 'Fiji',
    'fm': 'Micronesia',
    'fr': 'France',
    'ga': 'Gabon',
    'gb': 'United Kingdom',
    'gd': 'Grenada',
    'ge': 'Georgia',
    'gh': 'Ghana',
    'gm': 'The Gambia',
    'gn': 'Guinea',
    'gq': 'Equatorial Guinea',
    'gr': 'Greece',
    'gt': 'Guatemala',
    'gw': 'Guinea-Bissau',
    'gy': 'Guyana',
    'hn': 'Honduras',
    'hr': 'Croatia',
    'ht': 'Haiti',
    'hu': 'Hungary',
    'id': 'Indonesia',
    'ie': 'Ireland',
    'il': 'Israel',
    'in': 'India',
    'iq': 'Iraq',
    'ir': 'Iran',
    'is': 'Iceland',
    'it': 'Italy',
    'jm': 'Jamaica',
    'jo': 'Jordan',
    'jp': 'Japan',
    'ke': 'Kenya',
    'kg': 'Kyrgyzstan',
    'kh': 'Cambodia',
    'ki': 'Kiribati',
    'km': 'Comoros',
    'kn': 'Saint Kitts and Nevis',
    'kp': 'North Korea',
    'kr': 'South Korea',
    'kw': 'Kuwait',
    'kz': 'Kazakhstan',
    'la': 'Laos',
    'lb': 'Lebanon',
    'lc': 'Saint Lucia',
    'li': 'Liechtenstein',
    'lk': 'Sri Lanka',
    'lr': 'Liberia',
    'ls': 'Lesotho',
    'lt': 'Lithuania',
    'lu': 'Luxembourg',
    'lv': 'Latvia',
    'ly': 'Libya',
    'ma': 'Morocco',
    'mc': 'Monaco',
    'md': 'Moldova',
    'me': 'Montenegro',
    'mg': 'Madagascar',
    'mh': 'Marshall Islands',
    'mk': 'North Macedonia',
    'ml': 'Mali',
    'mm': 'Myanmar',
    'mn': 'Mongolia',
    'mr': 'Mauritania',
    'mt': 'Malta',
    'mu': 'Mauritius',
    'mv': 'Maldives',
    'mw': 'Malawi',
    'mx': 'Mexico',
    'my': 'Malaysia',
    'mz': 'Mozambique',
    'na': 'Namibia',
    'ne': 'Niger',
    'ng': 'Nigeria',
    'ni': 'Nicaragua',
    'nl': 'Netherlands',
    'no': 'Norway',
    'np': 'Nepal',
    'nr': 'Nauru',
    'nz': 'New Zealand',
    'om': 'Oman',
    'pa': 'Panama',
    'pe': 'Peru',
    'pg': 'Papua New Guinea',
    'ph': 'Philippines',
    'pk': 'Pakistan',
    'pl': 'Poland',
    'pt': 'Portugal',
    'pw': 'Palau',
    'py': 'Paraguay',
    'qa': 'Qatar',
    'ro': 'Romania',
    'rs': 'Serbia',
    'ru': 'Russia',
    'rw': 'Rwanda',
    'sa': 'Saudi Arabia',
    'sb': 'Solomon Islands',
    'sc': 'Seychelles',
    'sd': 'Sudan',
    'se': 'Sweden',
    'sg': 'Singapore',
    'si': 'Slovenia',
    'sk': 'Slovakia',
    'sl': 'Sierra Leone',
    'sm': 'San Marino',
    'sn': 'Senegal',
    'so': 'Somalia',
    'sr': 'Suriname',
    'ss': 'South Sudan',
    'st': 'São Tomé and Príncipe',
    'sv': 'El Salvador',
    'sy': 'Syria',
    'sz': 'Eswatini',
    'td': 'Chad',
    'tg': 'Togo',
    'th': 'Thailand',
    'tj': 'Tajikistan',
    'tl': 'Timor-Leste',
    'tm': 'Turkmenistan',
    'tn': 'Tunisia',
    'to': 'Tonga',
    'tr': 'Turkey',
    'tt': 'Trinidad and Tobago',
    'tv': 'Tuvalu',
    'tz': 'Tanzania',
    'ua': 'Ukraine',
    'ug': 'Uganda',
    'us': 'United States',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'vc': 'Saint Vincent and the Grenadines',
    've': 'Venezuela',
    'vn': 'Vietnam',
    'vu': 'Vanuatu',
    'ws': 'Samoa',
    'ye': 'Yemen',
    'za': 'South Africa',
    'zm': 'Zambia',
    'zw': 'Zimbabwe',
  };

  static const _be = {
    'ad': 'Андора',
    'ae': 'Аб’яднаныя Арабскія Эміраты',
    'af': 'Афганістан',
    'ag': 'Антыгуа і Барбуда',
    'al': 'Албанія',
    'am': 'Арменія',
    'ao': 'Ангола',
    'ar': 'Аргенціна',
    'at': 'Аўстрыя',
    'au': 'Аўстралія',
    'az': 'Азербайджан',
    'ba': 'Боснія і Герцагавіна',
    'bb': 'Барбадас',
    'bd': 'Бангладэш',
    'be': 'Бельгія',
    'bf': 'Буркіна-Фасо',
    'bg': 'Балгарыя',
    'bh': 'Бахрэйн',
    'bi': 'Бурундзі',
    'bj': 'Бенін',
    'bn': 'Бруней',
    'bo': 'Балівія',
    'br': 'Бразілія',
    'bs': 'Багамскія Астравы',
    'bt': 'Бутан',
    'bw': 'Батсвана',
    'by': 'Беларусь',
    'bz': 'Беліз',
    'ca': 'Канада',
    'cd': 'Дэмакратычная Рэспубліка Конга',
    'cf': 'Цэнтральна-Афрыканская Рэспубліка',
    'cg': 'Рэспубліка Конга',
    'ch': 'Швейцарыя',
    'ci': 'Кот-д’Івуар',
    'cl': 'Чылі',
    'cm': 'Камерун',
    'cn': 'Кітай',
    'co': 'Калумбія',
    'cr': 'Коста-Рыка',
    'cu': 'Куба',
    'cv': 'Каба-Вердэ',
    'cy': 'Кіпр',
    'cz': 'Чэхія',
    'de': 'Германія',
    'dj': 'Джыбуці',
    'dk': 'Данія',
    'dm': 'Дамініка',
    'do': 'Дамініканская Рэспубліка',
    'dz': 'Алжыр',
    'ec': 'Эквадор',
    'ee': 'Эстонія',
    'eg': 'Егіпет',
    'er': 'Эрытрэя',
    'es': 'Іспанія',
    'et': 'Эфіопія',
    'fi': 'Фінляндыя',
    'fj': 'Фіджы',
    'fm': 'Мікранезія',
    'fr': 'Францыя',
    'ga': 'Габон',
    'gb': 'Вялікабрытанія',
    'gd': 'Грэнада',
    'ge': 'Грузія',
    'gh': 'Гана',
    'gm': 'Гамбія',
    'gn': 'Гвінея',
    'gq': 'Экватарыяльная Гвінея',
    'gr': 'Грэцыя',
    'gt': 'Гватэмала',
    'gw': 'Гвінея-Бісаў',
    'gy': 'Гаяна',
    'hn': 'Гандурас',
    'hr': 'Харватыя',
    'ht': 'Гаіці',
    'hu': 'Венгрыя',
    'id': 'Інданезія',
    'ie': 'Ірландыя',
    'il': 'Ізраіль',
    'in': 'Індыя',
    'iq': 'Ірак',
    'ir': 'Іран',
    'is': 'Ісландыя',
    'it': 'Італія',
    'jm': 'Ямайка',
    'jo': 'Іарданія',
    'jp': 'Японія',
    'ke': 'Кенія',
    'kg': 'Кыргызстан',
    'kh': 'Камбоджа',
    'ki': 'Кірыбаці',
    'km': 'Каморскія Астравы',
    'kn': 'Сент-Кітс і Невіс',
    'kp': 'Паўночная Карэя',
    'kr': 'Паўднёвая Карэя',
    'kw': 'Кувейт',
    'kz': 'Казахстан',
    'la': 'Лаос',
    'lb': 'Ліван',
    'lc': 'Сент-Люсія',
    'li': 'Ліхтэнштэйн',
    'lk': 'Шры Ланка',
    'lr': 'Ліберыя',
    'ls': 'Лесота',
    'lt': 'Літва',
    'lu': 'Люксембург',
    'lv': 'Латвія',
    'ly': 'Лівія',
    'ma': 'Марока',
    'mc': 'Манака',
    'md': 'Малдова',
    'me': 'Чарнагорыя',
    'mg': 'Мадагаскар',
    'mh': 'Маршалавы Астравы',
    'mk': 'Паўночная Македонія',
    'ml': 'Малі',
    'mm': 'М\'янма',
    'mn': 'Манголія',
    'mr': 'Маўрытанія',
    'mt': 'Мальта',
    'mu': 'Маўрыкій',
    'mv': 'Мальдывы',
    'mw': 'Малаві',
    'mx': 'Мексіка',
    'my': 'Малайзія',
    'mz': 'Мазамбік',
    'na': 'Намібія',
    'ne': 'Нігер',
    'ng': 'Нігерыя',
    'ni': 'Нікарагуа',
    'nl': 'Нідэрланды',
    'no': 'Нарвегія',
    'np': 'Непал',
    'nr': 'Науру',
    'nz': 'Новая Зеландыя',
    'om': 'Аман',
    'pa': 'Панама',
    'pe': 'Перу',
    'pg': 'Папуа-Новая Гвінея',
    'ph': 'Філіпіны',
    'pk': 'Пакістан',
    'pl': 'Польшча',
    'pt': 'Партугалія',
    'pw': 'Палау',
    'py': 'Парагвай',
    'qa': 'Катар',
    'ro': 'Румынія',
    'rs': 'Сербія',
    'ru': 'Расія',
    'rw': 'Руанда',
    'sa': 'Саўдаўская Аравія',
    'sb': 'Саламонавы Астравы',
    'sc': 'Сейшэльскія Астравы',
    'sd': 'Судан',
    'se': 'Швецыя',
    'sg': 'Сінгапур',
    'si': 'Славенія',
    'sk': 'Славакія',
    'sl': 'Сьера-Леонэ',
    'sm': 'Сан-Марына',
    'sn': 'Сенегал',
    'so': 'Самалі',
    'sr': 'Сурынам',
    'ss': 'Паўднёвы Судан',
    'st': 'Сан-Тамэ і Прынсіпі',
    'sv': 'Сальвадор',
    'sy': 'Сірыя',
    'sz': 'Эсваціні',
    'td': 'Чад',
    'tg': 'Тога',
    'th': 'Тайланд',
    'tj': 'Таджыкістан',
    'tl': 'Усходні Тымор',
    'tm': 'Туркменістан',
    'tn': 'Туніс',
    'to': 'Тонга',
    'tr': 'Турцыя',
    'tt': 'Трынідад і Табага',
    'tv': 'Тувалу',
    'tz': 'Танзанія',
    'ua': 'Украіна',
    'ug': 'Уганда',
    'us': 'Злучаныя Штаты Амерыкі',
    'uy': 'Уругвай',
    'uz': 'Узбекістан',
    'vc': 'Сент-Вінсент і Грэнадзіны',
    've': 'Венесуэла',
    'vn': 'В\'етнам',
    'vu': 'Вануату',
    'ws': 'Самоа',
    'ye': 'Емен',
    'za': 'Паўднёва-Афрыканская Рэспубліка',
    'zm': 'Замбія',
    'zw': 'Зімбабвэ',
  };

  static const _cy = {
    'ad': 'Andorra',
    'ae': 'Yr Emiradau Arabaidd Unedig',
    'af': 'Affganistan',
    'ag': 'Antigwa a Barbiwda',
    'al': 'Albania',
    'am': 'Armenia',
    'ao': 'Angola',
    'ar': 'Yr Ariannin',
    'at': 'Awstria',
    'au': 'Awstralia',
    'az': 'Aserbaijan',
    'ba': 'Bosnia a Hertsegofina',
    'bb': 'Barbados',
    'bd': 'Bangladesh',
    'be': 'Gwlad Belg',
    'bf': 'Bwrcina Ffaso',
    'bg': 'Bwlgaria',
    'bh': 'Bahrain',
    'bi': 'Bwrwndi',
    'bj': 'Benin',
    'bn': 'Brwnei',
    'bo': 'Bolifia',
    'br': 'Brasil',
    'bs': 'Y Bahamas',
    'bt': 'Bhwtan',
    'bw': 'Botswana',
    'by': 'Belarws',
    'bz': 'Belîs',
    'ca': 'Canada',
    'cd': 'Gweriniaeth Ddemocrataidd y Congo',
    'cf': 'Gweriniaeth Canolbarth Affrica',
    'cg': 'Gweriniaeth y Congo',
    'ch': 'Y Swistir',
    'ci': 'Arfordir Ifori',
    'cl': 'Tsile',
    'cm': 'Camerŵn',
    'cn': 'Tsieina',
    'co': 'Colombia',
    'cr': 'Costa Rica',
    'cu': 'Ciwba',
    'cv': 'Cabo Verde',
    'cy': 'Cyprus',
    'cz': 'Y Weriniaeth Tsiec',
    'de': 'Yr Almaen',
    'dj': 'Jibwti',
    'dk': 'Denmarc',
    'dm': 'Dominica',
    'do': 'Gweriniaeth Dominica',
    'dz': 'Algeria',
    'ec': 'Ecwador',
    'ee': 'Estonia',
    'eg': 'Yr Aifft',
    'er': 'Eritrea',
    'es': 'Sbaen',
    'et': 'Ethiopia',
    'fi': 'Y Ffindir',
    'fj': 'Ffiji',
    'fm': 'Micronesia',
    'fr': 'Ffrainc',
    'ga': 'Gabon',
    'gb': 'Y Deyrnas Unedig',
    'gd': 'Grenada',
    'ge': 'Georgia',
    'gh': 'Ghana',
    'gm': 'Y Gambia',
    'gn': 'Gini',
    'gq': 'Gini Cyhydeddol',
    'gr': 'Gwlad Groeg',
    'gt': 'Gwatemala',
    'gw': 'Gini Bisaw',
    'gy': 'Gaiana',
    'hn': 'Hondwras',
    'hr': 'Croatia',
    'ht': 'Haiti',
    'hu': 'Hwngari',
    'id': 'Indonesia',
    'ie': 'Iwerddon',
    'il': 'Israel',
    'in': 'India',
    'iq': 'Irac',
    'ir': 'Iran',
    'is': 'Gwlad yr Iâ',
    'it': 'Yr Eidal',
    'jm': 'Jamaica',
    'jo': 'Gwlad Iorddonen',
    'jp': 'Japan',
    'ke': 'Cenia',
    'kg': 'Cirgistan',
    'kh': 'Cambodia',
    'ki': 'Ciribati',
    'km': 'Y Comoros',
    'kn': 'Sant Kitts-Nevis',
    'kp': 'Gogledd Corea',
    'kr': 'De Corea',
    'kw': 'Coweit',
    'kz': 'Casachstan',
    'la': 'Laos',
    'lb': 'Libanus',
    'lc': 'Sant Lwsia',
    'li': 'Liechtenstein',
    'lk': 'Sri Lanka',
    'lr': 'Liberia',
    'ls': 'Lesotho',
    'lt': 'Lithwania',
    'lu': 'Lwcsembwrg',
    'lv': 'Latfia',
    'ly': 'Libia',
    'ma': 'Moroco',
    'mc': 'Monaco',
    'md': 'Moldofa',
    'me': 'Montenegro',
    'mg': 'Madagascar',
    'mh': 'Ynysoedd Marshall',
    'mk': 'Gogledd Macedonia',
    'ml': 'Mali',
    'mm': 'Myanmar',
    'mn': 'Mongolia',
    'mr': 'Mawritania',
    'mt': 'Malta',
    'mu': 'Mawrisiws',
    'mv': 'Maldives',
    'mw': 'Malawi',
    'mx': 'Mecsico',
    'my': 'Maleisia',
    'mz': 'Mosambic',
    'na': 'Namibia',
    'ne': 'Niger',
    'ng': 'Nigeria',
    'ni': 'Nicaragwa',
    'nl': 'Yr Iseldiroedd',
    'no': 'Norwy',
    'np': 'Nepal',
    'nr': 'Nawrw',
    'nz': 'Seland Newydd',
    'om': 'Oman',
    'pa': 'Panama',
    'pe': 'Periw',
    'pg': 'Papua Gini Newydd',
    'ph': 'Y Philipinau',
    'pk': 'Pacistan',
    'pl': 'Gwlad Pwyl',
    'pt': 'Portiwgal',
    'pw': 'Palaw',
    'py': 'Paragwâi',
    'qa': 'Qatar',
    'ro': 'Rwmania',
    'rs': 'Serbia',
    'ru': 'Rwsia',
    'rw': 'Rwanda',
    'sa': 'Sawdi Arabia',
    'sb': 'Ynysoedd Solomon',
    'sc': 'Seychelles',
    'sd': 'Swdan',
    'se': 'Sweden',
    'sg': 'Singapôr',
    'si': 'Slofenia',
    'sk': 'Slofacia',
    'sl': 'Sierra Leone',
    'sm': 'San Marino',
    'sn': 'Senegal',
    'so': 'Somalia',
    'sr': 'Swrinam',
    'ss': 'De Swdan',
    'st': 'São Tomé a Príncipe',
    'sv': 'El Salfador',
    'sy': 'Syria',
    'sz': 'Eswatini',
    'td': 'Tsiad',
    'tg': 'Togo',
    'th': 'Gwlad Tai',
    'tj': 'Tajicistan',
    'tl': 'Dwyrain Timor',
    'tm': 'Tyrcmenistan',
    'tn': 'Tiwnisia',
    'to': 'Tonga',
    'tr': 'Twrci',
    'tt': 'Trinidad a Thobago',
    'tv': 'Twfalw',
    'tz': 'Tansanïa',
    'ua': 'Yr Wcráin',
    'ug': 'Wganda',
    'us': 'Unol Daleithiau',
    'uy': 'Wrwgwái',
    'uz': 'Wsbecistan',
    'vc': 'Saint Vincent a\'r Grenadines',
    've': 'Feneswela',
    'vn': 'Fietnam',
    'vu': 'Fanwatw',
    'ws': 'Samoa',
    'ye': 'Iemen',
    'za': 'De Affrica',
    'zm': 'Sambia',
    'zw': 'Simbabwe',
  };

  static const _ga = {
    'ad': 'Andóra',
    'ae': 'Aontas na nÉimíríochtaí Arabacha',
    'af': 'An Afganastáin',
    'ag': 'Antigua agus Barbúda',
    'al': 'An Albáin',
    'am': 'An Airméin',
    'ao': 'Angóla',
    'ar': 'An Airgintín',
    'at': 'An Ostair',
    'au': 'An Astráil',
    'az': 'An Asarbaiseáin',
    'ba': 'An Bhoisnia agus an Heirseagaivéin',
    'bb': 'Barbadós',
    'bd': 'An Bhanglaidéis',
    'be': 'An Bheilg',
    'bf': 'Buircíne Fasó',
    'bg': 'An Bhulgáir',
    'bh': 'Bairéin',
    'bi': 'An Bhurúin',
    'bj': 'Beinin',
    'bn': 'Brúiné',
    'bo': 'An Bholaiv',
    'br': 'An Bhrasaíl',
    'bs': 'Na Bahámaí',
    'bt': 'Bhútáin',
    'bw': 'Bhotsuáin',
    'by': 'An Bhealarúis',
    'bz': 'An Bheilís',
    'ca': 'Ceanada',
    'cd': 'Chongó (Poblacht Dhaonlathach an)',
    'cf': 'Poblacht na hAfraice Láir',
    'cg': 'Chongó (Poblacht an)',
    'ch': 'An Eilvéis',
    'ci': 'An Cósta Eabhair',
    'cl': 'An tSile',
    'cm': 'Camarún',
    'cn': 'An tSín',
    'co': 'An Cholóim',
    'cr': 'Cósta Ríce',
    'cu': 'Cúba',
    'cv': 'Rinn Verde',
    'cy': 'An Chipir',
    'cz': 'Poblacht na Seice',
    'de': 'An Ghearmáin',
    'dj': 'Djibouti',
    'dk': 'An Danmhairg',
    'dm': 'Doiminice',
    'do': 'An Phoblacht Dhoiminiceach',
    'dz': 'An Ailgéir',
    'ec': 'Eacuadór',
    'ee': 'An Eastóin',
    'eg': 'An Éigipt',
    'er': 'An Eiritré',
    'es': 'An Spáinn',
    'et': 'An Aetóip',
    'fi': 'An Fhionlainn',
    'fj': 'Fidsí',
    'fm': 'An Mhicrinéis',
    'fr': 'An Fhrainc',
    'ga': 'An Ghabúin',
    'gb': 'An Ríocht Aontaithe',
    'gd': 'Greanáda',
    'ge': 'An tSeoirsia',
    'gh': 'Gána',
    'gm': 'An Ghaimbia',
    'gn': 'An Guine',
    'gq': 'An Ghuine Mheánchriosach',
    'gr': 'An Ghréig',
    'gt': 'Guatamala',
    'gw': 'Guine Bissau',
    'gy': 'An Ghuáin',
    'hn': 'Hondúras',
    'hr': 'An Chróit',
    'ht': 'Háití',
    'hu': 'An Ungáir',
    'id': 'An Indinéis',
    'ie': 'Éire',
    'il': 'Iosrael',
    'in': 'An India',
    'iq': 'Iaráic',
    'ir': 'An Iaráin',
    'is': 'An Íoslainn',
    'it': 'An Iodáil',
    'jm': 'Iamáice',
    'jo': 'An Iordáin',
    'jp': 'An tSeapáin',
    'ke': 'An Chéinia',
    'kg': 'An Chirgeastáin',
    'kh': 'An Chambóid',
    'ki': 'Cireabaití',
    'km': 'Oileáin Chomóra',
    'kn': 'San Críostóir-Nimheas',
    'kp': 'An Chóiré Thuaidh',
    'kr': 'An Chóiré Theas',
    'kw': 'Cuáit',
    'kz': 'An Chasacstáin',
    'la': 'Laos',
    'lb': 'An Liobáin',
    'lc': 'Saint Lucia',
    'li': 'Lichtinstéin',
    'lk': 'Srí Lanca',
    'lr': 'An Libéir',
    'ls': 'Leosóta',
    'lt': 'An Liotuáin',
    'lu': 'Lucsamburg',
    'lv': 'An Laitvia',
    'ly': 'An Libia',
    'ma': 'Maracó',
    'mc': 'Monacó',
    'md': 'An Mholdóiv',
    'me': 'Montainéagró',
    'mg': 'Madagascar',
    'mh': 'Oileáin Marshall',
    'mk': 'An Mhacadóin Thuaidh',
    'ml': 'Mailí',
    'mm': 'Maenmar',
    'mn': 'An Mhongóil',
    'mr': 'An Mháratáin',
    'mt': 'Málta',
    'mu': 'Oileán Mhuirís',
    'mv': 'Oileáin Mhaildíve',
    'mw': 'An Mhaláiv',
    'mx': 'Meicsiceo',
    'my': 'An Mhalaeisia',
    'mz': 'Mósaimbíc',
    'na': 'An Namaib',
    'ne': 'An Nígir',
    'ng': 'An Nigéir',
    'ni': 'Nicearagua',
    'nl': 'An Ísiltír',
    'no': 'An Iorua',
    'np': 'Neipeal',
    'nr': 'Nárú',
    'nz': 'An Nua-Shéalainn',
    'om': 'Óman',
    'pa': 'Panama',
    'pe': 'Peiriú',
    'pg': 'Nua-Ghuine Phapua',
    'ph': 'Na hOileáin Fhilipíneacha',
    'pk': 'An Phacastáin',
    'pl': 'An Pholainn',
    'pt': 'An Phortaingéil',
    'pw': 'Oileáin Palau',
    'py': 'Paragua',
    'qa': 'Catar',
    'ro': 'An Rómáin',
    'rs': 'An tSeirbia',
    'ru': 'An Rúis',
    'rw': 'Ruanda',
    'sa': 'An Araib Shádach',
    'sb': 'Oileáin Sholamón',
    'sc': 'Na Séiséil',
    'sd': 'An tSúdáin',
    'se': 'An tSualainn',
    'sg': 'Singeapór',
    'si': 'An tSlóivéin',
    'sk': 'An tSlóvaic',
    'sl': 'Siarra Leon',
    'sm': 'San Mairíne',
    'sn': 'An tSeineagáil',
    'so': 'An tSomáil',
    'sr': 'Suranam',
    'ss': 'An tSúdáin Theas',
    'st': 'São Tomé agus Príncipe',
    'sv': 'An tSalvadóir',
    'sy': 'An tSiria',
    'sz': 'An tSuasalainn',
    'td': 'Sead',
    'tg': 'Tóga',
    'th': 'An Téalainn',
    'tj': 'An Táidsíceastáin',
    'tl': 'Tíomór-Leste',
    'tm': 'An Tuircméanastáin',
    'tn': 'An Túinéis',
    'to': 'Tonga',
    'tr': 'An Tuirc',
    'tt': 'Oileán na Tríonóide agus Tobága',
    'tv': 'Túvalú',
    'tz': 'An Tansáin',
    'ua': 'An Úcráin',
    'ug': 'Uganda',
    'us': 'Stáit Aontaithe Mheiriceá',
    'uy': 'Uragua',
    'uz': 'An Úisbéiceastáin',
    'vc': 'San Uinseann agus na Greanáidíní',
    've': 'Veiniséala',
    'vn': 'Vítneam',
    'vu': 'Vanuatú',
    'ws': 'Samó',
    'ye': 'Éimin',
    'za': 'An Afraic Theas',
    'zm': 'An tSaimbia',
    'zw': 'An tSiombáib',
  };

  static final _locales = {
    'en': _en,
    'be': _be,
    'cy': _cy,
    'ga': _ga,
  };
}

class _$CountryLocalizationsDelegate {
  static final _supportedLocales = {
    const Locale('en'),
    const Locale('be'),
    const Locale('cy'),
    const Locale('ga'),
  };
}
