// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_final_fields, public_member_api_docs, prefer_single_quotes, omit_local_variable_types, unnecessary_this

import 'dart:async';

import 'package:flutter/material.dart';

/// A  class generated by flappy_translator package containing localized strings
class AppLocalizations {
  static String get test => _getText('test');

  static String get generalNo => _getText('generalNo');

  static String get generalYes => _getText('generalYes');

  static String get generalContinue => _getText('generalContinue');

  static String generalLevelLabel({
    @required int level,
  }) {
    String text = _getText('generalLevelLabel');
    if (level != null) {
      text = text.replaceAll("%level\$d", level.toString());
    }
    return text;
  }

  static String get homeTabLabelText => _getText('homeTabLabelText');

  static String get homeTabLeanFlagsButtonText =>
      _getText('homeTabLeanFlagsButtonText');

  static String get settingsTabLabelText => _getText('settingsTabLabelText');

  static String get settingsTabLanguageLabel =>
      _getText('settingsTabLanguageLabel');

  static String get settingsTabResetProgressLabel =>
      _getText('settingsTabResetProgressLabel');

  static String get hardDifficultyPanelLabel =>
      _getText('hardDifficultyPanelLabel');

  static String get resetProgressDialogTitle =>
      _getText('resetProgressDialogTitle');

  static String get resetProgressDialogDescription =>
      _getText('resetProgressDialogDescription');

  static String get quitGameDialogTitle => _getText('quitGameDialogTitle');

  static String get quitGameDialogDescription =>
      _getText('quitGameDialogDescription');

  static String get onboardingPage1TextLabel1 =>
      _getText('onboardingPage1TextLabel1');

  static String get onboardingPage1TextLabel2 =>
      _getText('onboardingPage1TextLabel2');

  static String get onboardingPage1TextLabel3 =>
      _getText('onboardingPage1TextLabel3');

  static String get onboardingGeneralSettingLabel =>
      _getText('onboardingGeneralSettingLabel');

  static String get onboardingPage2TextLabel1 =>
      _getText('onboardingPage2TextLabel1');

  static String get onboardingPage2TextLabel2 =>
      _getText('onboardingPage2TextLabel2');

  static String get onboardingPage3TextLabel1 =>
      _getText('onboardingPage3TextLabel1');

  static String get onboardingPage3TextLabel2 =>
      _getText('onboardingPage3TextLabel2');

  static String get onboardingPage3TextLabel3 =>
      _getText('onboardingPage3TextLabel3');

  static String get developerPanelLabel => _getText('developerPanelLabel');

  static String get dataPrivacyPanelLabel1 =>
      _getText('dataPrivacyPanelLabel1');

  static String get dataPrivacyPanelLabel2 =>
      _getText('dataPrivacyPanelLabel2');

  static Map<String, String> _localizedValues;

  static Map<String, String> _enValues = {
    'test': 'Hello World!',
    'generalNo': 'No',
    'generalYes': 'Yes',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Home',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Settings',
    'settingsTabLanguageLabel': 'Language',
    'settingsTabResetProgressLabel': 'Reset Progress',
    'hardDifficultyPanelLabel': 'Hard Difficulty',
    'resetProgressDialogTitle': 'Reset progress?',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
    'onboardingPage1TextLabel1': 'Bratacha',
    'onboardingPage1TextLabel2':
        'A fun flag quiz game with an emphasis on often overlooked languages.',
    'onboardingPage1TextLabel3': 'What language would you like to use?',
    'onboardingGeneralSettingLabel':
        'This can be changed anything in the settings menu.',
    'onboardingPage2TextLabel1': 'Fancy a challenge?',
    'onboardingPage2TextLabel2':
        'Earn extra points by enabling hard difficulty!',
    'onboardingPage3TextLabel1':
        'Bratacha is an open source project targeting languages which are often ignored within the flag quiz space.',
    'onboardingPage3TextLabel2':
        'If you\'d like to help translating the app into Irish/Welsh/Belarusian, please get in touch! Likewise if you\'d like to work on another language!',
    'onboardingPage3TextLabel3':
        'As the game is presently in development, all content is subject to change. Your feedback is greatly appreciated!',
    'developerPanelLabel':
        'Developed with \u2764 in Berlin. [Source Code](https://github.com/defuncart/bratacha).',
    'dataPrivacyPanelLabel1':
        'By using this application, you agree to the terms and conditions stated in the [privacy policy](https://github.com/defuncart/bratacha/blob/master/privacy_policy.md).',
    'dataPrivacyPanelLabel2':
        'No data is collected on how you use the app, nor is any data sent onto third parties.',
  };

  static Map<String, String> _beValues = {
    'test': 'Здароўствуй свет!',
    'generalNo': 'Не',
    'generalYes': 'Так',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Галоўная',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Налады',
    'settingsTabLanguageLabel': 'Мова',
    'settingsTabResetProgressLabel': 'Скід прагрэсу',
    'hardDifficultyPanelLabel': 'Складаная складанасць',
    'resetProgressDialogTitle': 'Reset progress?',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
    'onboardingPage1TextLabel1': 'Bratacha',
    'onboardingPage1TextLabel2':
        'A fun flag quiz game with an emphasis on often overlooked languages.',
    'onboardingPage1TextLabel3': 'What language would you like to use?',
    'onboardingGeneralSettingLabel':
        'This can be changed anything in the settings menu.',
    'onboardingPage2TextLabel1': 'Fancy a challenge?',
    'onboardingPage2TextLabel2':
        'Earn extra points by enabling hard difficulty!',
    'onboardingPage3TextLabel1':
        'Bratacha is an open source project targeting languages which are often ignored within the flag quiz space.',
    'onboardingPage3TextLabel2':
        'If you\'d like to help translating the app into Irish/Welsh/Belarusian, please get in touch! Likewise if you\'d like to work on another language!',
    'onboardingPage3TextLabel3':
        'As the game is presently in development, all content is subject to change. Your feedback is greatly appreciated!',
    'developerPanelLabel':
        'Developed with \u2764 in Berlin. [Source Code](https://github.com/defuncart/bratacha).',
    'dataPrivacyPanelLabel1':
        'By using this application, you agree to the terms and conditions stated in the [privacy policy](https://github.com/defuncart/bratacha/blob/master/privacy_policy.md).',
    'dataPrivacyPanelLabel2':
        'No data is collected on how you use the app, nor is any data sent onto third parties.',
  };

  static Map<String, String> _cyValues = {
    'test': 'Helo Byd!',
    'generalNo': 'Na',
    'generalYes': 'Ie',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Home',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Settings',
    'settingsTabLanguageLabel': 'Iaith',
    'settingsTabResetProgressLabel': 'Reset Progress',
    'hardDifficultyPanelLabel': 'Hard Difficulty',
    'resetProgressDialogTitle': 'Reset progress?',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
    'onboardingPage1TextLabel1': 'Bratacha',
    'onboardingPage1TextLabel2':
        'A fun flag quiz game with an emphasis on often overlooked languages.',
    'onboardingPage1TextLabel3': 'What language would you like to use?',
    'onboardingGeneralSettingLabel':
        'This can be changed anything in the settings menu.',
    'onboardingPage2TextLabel1': 'Fancy a challenge?',
    'onboardingPage2TextLabel2':
        'Earn extra points by enabling hard difficulty!',
    'onboardingPage3TextLabel1':
        'Bratacha is an open source project targeting languages which are often ignored within the flag quiz space.',
    'onboardingPage3TextLabel2':
        'If you\'d like to help translating the app into Irish/Welsh/Belarusian, please get in touch! Likewise if you\'d like to work on another language!',
    'onboardingPage3TextLabel3':
        'As the game is presently in development, all content is subject to change. Your feedback is greatly appreciated!',
    'developerPanelLabel':
        'Developed with \u2764 in Berlin. [Source Code](https://github.com/defuncart/bratacha).',
    'dataPrivacyPanelLabel1':
        'By using this application, you agree to the terms and conditions stated in the [privacy policy](https://github.com/defuncart/bratacha/blob/master/privacy_policy.md).',
    'dataPrivacyPanelLabel2':
        'No data is collected on how you use the app, nor is any data sent onto third parties.',
  };

  static Map<String, String> _gaValues = {
    'test': 'Dia duit domhan!',
    'generalNo': 'No',
    'generalYes': 'Yes',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Home',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Settings',
    'settingsTabLanguageLabel': 'Teanga',
    'settingsTabResetProgressLabel': 'Reset Progress',
    'hardDifficultyPanelLabel': 'Hard Difficulty',
    'resetProgressDialogTitle': ' ',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
    'onboardingPage1TextLabel1': 'Bratacha',
    'onboardingPage1TextLabel2':
        'A fun flag quiz game with an emphasis on often overlooked languages.',
    'onboardingPage1TextLabel3': 'What language would you like to use?',
    'onboardingGeneralSettingLabel':
        'This can be changed anything in the settings menu.',
    'onboardingPage2TextLabel1': 'Fancy a challenge?',
    'onboardingPage2TextLabel2':
        'Earn extra points by enabling hard difficulty!',
    'onboardingPage3TextLabel1':
        'Bratacha is an open source project targeting languages which are often ignored within the flag quiz space.',
    'onboardingPage3TextLabel2':
        'If you\'d like to help translating the app into Irish/Welsh/Belarusian, please get in touch! Likewise if you\'d like to work on another language!',
    'onboardingPage3TextLabel3':
        'As the game is presently in development, all content is subject to change. Your feedback is greatly appreciated!',
    'developerPanelLabel':
        'Developed with \u2764 in Berlin. [Source Code](https://github.com/defuncart/bratacha).',
    'dataPrivacyPanelLabel1':
        'By using this application, you agree to the terms and conditions stated in the [privacy policy](https://github.com/defuncart/bratacha/blob/master/privacy_policy.md).',
    'dataPrivacyPanelLabel2':
        'No data is collected on how you use the app, nor is any data sent onto third parties.',
  };

  static Map<String, Map<String, String>> _allValues = {
    'en': _enValues,
    'be': _beValues,
    'cy': _cyValues,
    'ga': _gaValues,
  };

  AppLocalizations(Locale locale) {
    _locale = locale;
    _localizedValues = null;
  }

  static Locale _locale;

  static String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  static Locale get currentLocale => _locale;

  static String get currentLanguage => _locale.languageCode;

  static Future<AppLocalizations> load(Locale locale) async {
    final translations = AppLocalizations(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('be'),
    Locale('cy'),
    Locale('ga'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<AppLocalizations> load(Locale locale) => AppLocalizations.load(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
