// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_final_fields, public_member_api_docs, prefer_single_quotes, omit_local_variable_types, unnecessary_this

import 'dart:async';

import 'package:flutter/material.dart';

/// A  class generated by flappy_translator package containing localized strings
class AppLocalizations {
  static String get test => _getText('test');

  static String get generalContinue => _getText('generalContinue');

  static String generalLevelLabel({
    @required int level,
  }) {
    String text = _getText('generalLevelLabel');
    if (level != null) {
      text = text.replaceAll("%level\$d", level.toString());
    }
    return text;
  }

  static String get homeTabLabelText => _getText('homeTabLabelText');

  static String get homeTabLeanFlagsButtonText =>
      _getText('homeTabLeanFlagsButtonText');

  static String get settingsTabLabelText => _getText('settingsTabLabelText');

  static String get settingsTabLanguageLabel =>
      _getText('settingsTabLanguageLabel');

  static String get settingsTabDifficultyLabel =>
      _getText('settingsTabDifficultyLabel');

  static String get settingsTabResetProgressLabel =>
      _getText('settingsTabResetProgressLabel');

  static String get resetProgressDialogTitle =>
      _getText('resetProgressDialogTitle');

  static String get resetProgressDialogDescription =>
      _getText('resetProgressDialogDescription');

  static String get generalNo => _getText('generalNo');

  static String get generalYes => _getText('generalYes');

  static String get quitGameDialogTitle => _getText('quitGameDialogTitle');

  static String get quitGameDialogDescription =>
      _getText('quitGameDialogDescription');

  static Map<String, String> _localizedValues;

  static Map<String, String> _enValues = {
    'test': 'Hello World!',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Home',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Settings',
    'settingsTabLanguageLabel': 'Language',
    'settingsTabDifficultyLabel': 'Hard Difficulty',
    'settingsTabResetProgressLabel': 'Reset Progress',
    'resetProgressDialogTitle': 'Reset progress?',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'generalNo': 'No',
    'generalYes': 'Yes',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
  };

  static Map<String, String> _beValues = {
    'test': 'Здароўствуй свет!',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Галоўная',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Налады',
    'settingsTabLanguageLabel': 'Мова',
    'settingsTabDifficultyLabel': 'Складаная складанасць',
    'settingsTabResetProgressLabel': 'Скід прагрэсу',
    'resetProgressDialogTitle': 'Reset progress?',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'generalNo': 'Не',
    'generalYes': 'Так',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
  };

  static Map<String, String> _cyValues = {
    'test': 'Helo Byd!',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Home',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Settings',
    'settingsTabLanguageLabel': 'Language',
    'settingsTabDifficultyLabel': 'Hard Difficulty',
    'settingsTabResetProgressLabel': 'Reset Progress',
    'resetProgressDialogTitle': 'Reset progress?',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'generalNo': 'Na',
    'generalYes': 'Ie',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
  };

  static Map<String, String> _gaValues = {
    'test': 'Dia duit domhan!',
    'generalContinue': 'Continue',
    'generalLevelLabel': 'Level %level\$d',
    'homeTabLabelText': 'Home',
    'homeTabLeanFlagsButtonText': 'See all flags',
    'settingsTabLabelText': 'Settings',
    'settingsTabLanguageLabel': 'Language',
    'settingsTabDifficultyLabel': 'Hard Difficulty',
    'settingsTabResetProgressLabel': 'Reset Progress',
    'resetProgressDialogTitle': ' ',
    'resetProgressDialogDescription':
        'Your progress will be permantely deleted and cannot be recovered.',
    'generalNo': 'No',
    'generalYes': 'Yes',
    'quitGameDialogTitle': 'Quit Game?',
    'quitGameDialogDescription': 'Your current progress will be lost.',
  };

  static Map<String, Map<String, String>> _allValues = {
    'en': _enValues,
    'be': _beValues,
    'cy': _cyValues,
    'ga': _gaValues,
  };

  AppLocalizations(Locale locale) {
    _locale = locale;
    _localizedValues = null;
  }

  static Locale _locale;

  static String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  static Locale get currentLocale => _locale;

  static String get currentLanguage => _locale.languageCode;

  static Future<AppLocalizations> load(Locale locale) async {
    final translations = AppLocalizations(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('be'),
    Locale('cy'),
    Locale('ga'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<AppLocalizations> load(Locale locale) => AppLocalizations.load(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
