// GENERATED CODE - DO NOT MODIFY BY HAND
part of 'country_localizations.dart';

mixin _$CountryLocalizations {
  static const _en = {
    'adName': 'Andorra',
    'aeName': 'United Arab Emirates',
    'afName': 'Afghanistan',
    'agName': 'Antigua and Barbuda',
    'alName': 'Albania',
    'amName': 'Armenia',
    'aoName': 'Angola',
    'arName': 'Argentina',
    'atName': 'Austria',
    'auName': 'Australia',
    'azName': 'Azerbaijan',
    'baName': 'Bosnia and Herzegovina',
    'bbName': 'Barbados',
    'bdName': 'Bangladesh',
    'beName': 'Belgium',
    'bfName': 'Burkina Faso',
    'bgName': 'Bulgaria',
    'bhName': 'Bahrain',
    'biName': 'Burundi',
    'bjName': 'Benin',
    'bnName': 'Brunei',
    'boName': 'Bolivia',
    'brName': 'Brazil',
    'bsName': 'The Bahamas',
    'btName': 'Bhutan',
    'bwName': 'Botswana',
    'byName': 'Belarus',
    'bzName': 'Belize',
    'caName': 'Canada',
    'cdName': 'Congo (Democratic Republic of)',
    'cfName': 'Central African Republic',
    'cgName': 'Congo (Republic of)',
    'chName': 'Switzerland',
    'ciName': 'Ivory Coast',
    'clName': 'Chile',
    'cmName': 'Cameroon',
    'cnName': 'China',
    'coName': 'Colombia',
    'crName': 'Costa Rica',
    'cuName': 'Cuba',
    'cvName': 'Cape Verde',
    'cyName': 'Cyprus',
    'czName': 'Czech Republic',
    'deName': 'Germany',
    'djName': 'Djibouti',
    'dkName': 'Denmark',
    'dmName': 'Dominica',
    'doName': 'Dominican Republic',
    'dzName': 'Algeria',
    'ecName': 'Ecuador',
    'eeName': 'Estonia',
    'egName': 'Egypt',
    'erName': 'Eritrea',
    'esName': 'Spain',
    'etName': 'Ethiopia',
    'fiName': 'Finland',
    'fjName': 'Fiji',
    'fmName': 'Micronesia',
    'frName': 'France',
    'gaName': 'Gabon',
    'gbName': 'United Kingdom',
    'gdName': 'Grenada',
    'geName': 'Georgia',
    'ghName': 'Ghana',
    'gmName': 'The Gambia',
    'gnName': 'Guinea',
    'gqName': 'Equatorial Guinea',
    'grName': 'Greece',
    'gtName': 'Guatemala',
    'gwName': 'Guinea-Bissau',
    'gyName': 'Guyana',
    'hnName': 'Honduras',
    'hrName': 'Croatia',
    'htName': 'Haiti',
    'huName': 'Hungary',
    'idName': 'Indonesia',
    'ieName': 'Ireland',
    'ilName': 'Israel',
    'inName': 'India',
    'iqName': 'Iraq',
    'irName': 'Iran',
    'isName': 'Iceland',
    'itName': 'Italy',
    'jmName': 'Jamaica',
    'joName': 'Jordan',
    'jpName': 'Japan',
    'keName': 'Kenya',
    'kgName': 'Kyrgyzstan',
    'khName': 'Cambodia',
    'kiName': 'Kiribati',
    'kmName': 'Comoros',
    'knName': 'Saint Kitts and Nevis',
    'kpName': 'North Korea',
    'krName': 'South Korea',
    'kwName': 'Kuwait',
    'kzName': 'Kazakhstan',
    'laName': 'Laos',
    'lbName': 'Lebanon',
    'lcName': 'Saint Lucia',
    'liName': 'Liechtenstein',
    'lkName': 'Sri Lanka',
    'lrName': 'Liberia',
    'lsName': 'Lesotho',
    'ltName': 'Lithuania',
    'luName': 'Luxembourg',
    'lvName': 'Latvia',
    'lyName': 'Libya',
    'maName': 'Morocco',
    'mcName': 'Monaco',
    'mdName': 'Moldova',
    'meName': 'Montenegro',
    'mgName': 'Madagascar',
    'mhName': 'Marshall Islands',
    'mkName': 'North Macedonia',
    'mlName': 'Mali',
    'mmName': 'Myanmar',
    'mnName': 'Mongolia',
    'mrName': 'Mauritania',
    'mtName': 'Malta',
    'muName': 'Mauritius',
    'mvName': 'Maldives',
    'mwName': 'Malawi',
    'mxName': 'Mexico',
    'myName': 'Malaysia',
    'mzName': 'Mozambique',
    'naName': 'Namibia',
    'neName': 'Niger',
    'ngName': 'Nigeria',
    'niName': 'Nicaragua',
    'nlName': 'Netherlands',
    'noName': 'Norway',
    'npName': 'Nepal',
    'nrName': 'Nauru',
    'nzName': 'New Zealand',
    'omName': 'Oman',
    'paName': 'Panama',
    'peName': 'Peru',
    'pgName': 'Papua New Guinea',
    'phName': 'Philippines',
    'pkName': 'Pakistan',
    'plName': 'Poland',
    'ptName': 'Portugal',
    'pwName': 'Palau',
    'pyName': 'Paraguay',
    'qaName': 'Qatar',
    'roName': 'Romania',
    'rsName': 'Serbia',
    'ruName': 'Russia',
    'rwName': 'Rwanda',
    'saName': 'Saudi Arabia',
    'sbName': 'Solomon Islands',
    'scName': 'Seychelles',
    'sdName': 'Sudan',
    'seName': 'Sweden',
    'sgName': 'Singapore',
    'siName': 'Slovenia',
    'skName': 'Slovakia',
    'slName': 'Sierra Leone',
    'smName': 'San Marino',
    'snName': 'Senegal',
    'soName': 'Somalia',
    'srName': 'Suriname',
    'ssName': 'South Sudan',
    'stName': 'São Tomé and Príncipe',
    'svName': 'El Salvador',
    'syName': 'Syria',
    'szName': 'Eswatini',
    'tdName': 'Chad',
    'tgName': 'Togo',
    'thName': 'Thailand',
    'tjName': 'Tajikistan',
    'tlName': 'Timor-Leste',
    'tmName': 'Turkmenistan',
    'tnName': 'Tunisia',
    'toName': 'Tonga',
    'trName': 'Turkey',
    'ttName': 'Trinidad and Tobago',
    'tvName': 'Tuvalu',
    'tzName': 'Tanzania',
    'uaName': 'Ukraine',
    'ugName': 'Uganda',
    'usName': 'United States',
    'uyName': 'Uruguay',
    'uzName': 'Uzbekistan',
    'vcName': 'Saint Vincent and the Grenadines',
    'veName': 'Venezuela',
    'vnName': 'Vietnam',
    'vuName': 'Vanuatu',
    'wsName': 'Samoa',
    'yeName': 'Yemen',
    'zaName': 'South Africa',
    'zmName': 'Zambia',
    'zwName': 'Zimbabwe',
  };

  static const _by = {
    'adName': 'Андора',
    'aeName': 'Аб’яднаныя Арабскія Эміраты',
    'afName': 'Афганістан',
    'agName': 'Антыгуа і Барбуда',
    'alName': 'Албанія',
    'amName': 'Арменія',
    'aoName': 'Ангола',
    'arName': 'Аргенціна',
    'atName': 'Аўстрыя',
    'auName': 'Аўстралія',
    'azName': 'Азербайджан',
    'baName': 'Боснія і Герцагавіна',
    'bbName': 'Барбадас',
    'bdName': 'Бангладэш',
    'beName': 'Бельгія',
    'bfName': 'Буркіна-Фасо',
    'bgName': 'Балгарыя',
    'bhName': 'Бахрэйн',
    'biName': 'Бурундзі',
    'bjName': 'Бенін',
    'bnName': 'Бруней',
    'boName': 'Балівія',
    'brName': 'Бразілія',
    'bsName': 'Багамскія Астравы',
    'btName': 'Бутан',
    'bwName': 'Батсвана',
    'byName': 'Беларусь',
    'bzName': 'Беліз',
    'caName': 'Канада',
    'cdName': 'Дэмакратычная Рэспубліка Конга',
    'cfName': 'Цэнтральна-Афрыканская Рэспубліка',
    'cgName': 'Рэспубліка Конга',
    'chName': 'Швейцарыя',
    'ciName': 'Кот-д’Івуар',
    'clName': 'Чылі',
    'cmName': 'Камерун',
    'cnName': 'Кітай',
    'coName': 'Калумбія',
    'crName': 'Коста-Рыка',
    'cuName': 'Куба',
    'cvName': 'Каба-Вердэ',
    'cyName': 'Кіпр',
    'czName': 'Чэхія',
    'deName': 'Германія',
    'djName': 'Джыбуці',
    'dkName': 'Данія',
    'dmName': 'Дамініка',
    'doName': 'Дамініканская Рэспубліка',
    'dzName': 'Алжыр',
    'ecName': 'Эквадор',
    'eeName': 'Эстонія',
    'egName': 'Егіпет',
    'erName': 'Эрытрэя',
    'esName': 'Іспанія',
    'etName': 'Эфіопія',
    'fiName': 'Фінляндыя',
    'fjName': 'Фіджы',
    'fmName': 'Мікранезія',
    'frName': 'Францыя',
    'gaName': 'Габон',
    'gbName': 'Вялікабрытанія',
    'gdName': 'Грэнада',
    'geName': 'Грузія',
    'ghName': 'Гана',
    'gmName': 'Гамбія',
    'gnName': 'Гвінея',
    'gqName': 'Экватарыяльная Гвінея',
    'grName': 'Грэцыя',
    'gtName': 'Гватэмала',
    'gwName': 'Гвінея-Бісаў',
    'gyName': 'Гаяна',
    'hnName': 'Гандурас',
    'hrName': 'Харватыя',
    'htName': 'Гаіці',
    'huName': 'Венгрыя',
    'idName': 'Інданезія',
    'ieName': 'Ірландыя',
    'ilName': 'Ізраіль',
    'inName': 'Індыя',
    'iqName': 'Ірак',
    'irName': 'Іран',
    'isName': 'Ісландыя',
    'itName': 'Італія',
    'jmName': 'Ямайка',
    'joName': 'Іарданія',
    'jpName': 'Японія',
    'keName': 'Кенія',
    'kgName': 'Кыргызстан',
    'khName': 'Камбоджа',
    'kiName': 'Кірыбаці',
    'kmName': 'Каморскія Астравы',
    'knName': 'Сент-Кітс і Невіс',
    'kpName': 'Паўночная Карэя',
    'krName': 'Паўднёвая Карэя',
    'kwName': 'Кувейт',
    'kzName': 'Казахстан',
    'laName': 'Лаос',
    'lbName': 'Ліван',
    'lcName': 'Сент-Люсія',
    'liName': 'Ліхтэнштэйн',
    'lkName': 'Шры Ланка',
    'lrName': 'Ліберыя',
    'lsName': 'Лесота',
    'ltName': 'Літва',
    'luName': 'Люксембург',
    'lvName': 'Латвія',
    'lyName': 'Лівія',
    'maName': 'Марока',
    'mcName': 'Манака',
    'mdName': 'Малдова',
    'meName': 'Чарнагорыя',
    'mgName': 'Мадагаскар',
    'mhName': 'Маршалавы Астравы',
    'mkName': 'Паўночная Македонія',
    'mlName': 'Малі',
    'mmName': 'М\'янма',
    'mnName': 'Манголія',
    'mrName': 'Маўрытанія',
    'mtName': 'Мальта',
    'muName': 'Маўрыкій',
    'mvName': 'Мальдывы',
    'mwName': 'Малаві',
    'mxName': 'Мексіка',
    'myName': 'Малайзія',
    'mzName': 'Мазамбік',
    'naName': 'Намібія',
    'neName': 'Нігер',
    'ngName': 'Нігерыя',
    'niName': 'Нікарагуа',
    'nlName': 'Нідэрланды',
    'noName': 'Нарвегія',
    'npName': 'Непал',
    'nrName': 'Науру',
    'nzName': 'Новая Зеландыя',
    'omName': 'Аман',
    'paName': 'Панама',
    'peName': 'Перу',
    'pgName': 'Папуа-Новая Гвінея',
    'phName': 'Філіпіны',
    'pkName': 'Пакістан',
    'plName': 'Польшча',
    'ptName': 'Партугалія',
    'pwName': 'Палау',
    'pyName': 'Парагвай',
    'qaName': 'Катар',
    'roName': 'Румынія',
    'rsName': 'Сербія',
    'ruName': 'Расія',
    'rwName': 'Руанда',
    'saName': 'Саўдаўская Аравія',
    'sbName': 'Саламонавы Астравы',
    'scName': 'Сейшэльскія Астравы',
    'sdName': 'Судан',
    'seName': 'Швецыя',
    'sgName': 'Сінгапур',
    'siName': 'Славенія',
    'skName': 'Славакія',
    'slName': 'Сьера-Леонэ',
    'smName': 'Сан-Марына',
    'snName': 'Сенегал',
    'soName': 'Самалі',
    'srName': 'Сурынам',
    'ssName': 'Паўднёвы Судан',
    'stName': 'Сан-Тамэ і Прынсіпі',
    'svName': 'Сальвадор',
    'syName': 'Сірыя',
    'szName': 'Эсваціні',
    'tdName': 'Чад',
    'tgName': 'Тога',
    'thName': 'Тайланд',
    'tjName': 'Таджыкістан',
    'tlName': 'Усходні Тымор',
    'tmName': 'Туркменістан',
    'tnName': 'Туніс',
    'toName': 'Тонга',
    'trName': 'Турцыя',
    'ttName': 'Трынідад і Табага',
    'tvName': 'Тувалу',
    'tzName': 'Танзанія',
    'uaName': 'Украіна',
    'ugName': 'Уганда',
    'usName': 'Злучаныя Штаты Амерыкі',
    'uyName': 'Уругвай',
    'uzName': 'Узбекістан',
    'vcName': 'Сент-Вінсент і Грэнадзіны',
    'veName': 'Венесуэла',
    'vnName': 'В\'етнам',
    'vuName': 'Вануату',
    'wsName': 'Самоа',
    'yeName': 'Емен',
    'zaName': 'Паўднёва-Афрыканская Рэспубліка',
    'zmName': 'Замбія',
    'zwName': 'Зімбабвэ',
  };

  static const _cy = {
    'adName': 'Andorra',
    'aeName': 'Yr Emiradau Arabaidd Unedig',
    'afName': 'Affganistan',
    'agName': 'Antigwa a Barbiwda',
    'alName': 'Albania',
    'amName': 'Armenia',
    'aoName': 'Angola',
    'arName': 'Yr Ariannin',
    'atName': 'Awstria',
    'auName': 'Awstralia',
    'azName': 'Aserbaijan',
    'baName': 'Bosnia a Hertsegofina',
    'bbName': 'Barbados',
    'bdName': 'Bangladesh',
    'beName': 'Gwlad Belg',
    'bfName': 'Bwrcina Ffaso',
    'bgName': 'Bwlgaria',
    'bhName': 'Bahrain',
    'biName': 'Bwrwndi',
    'bjName': 'Benin',
    'bnName': 'Brwnei',
    'boName': 'Bolifia',
    'brName': 'Brasil',
    'bsName': 'Y Bahamas',
    'btName': 'Bhwtan',
    'bwName': 'Botswana',
    'byName': 'Belarws',
    'bzName': 'Belîs',
    'caName': 'Canada',
    'cdName': 'Gweriniaeth Ddemocrataidd y Congo',
    'cfName': 'Gweriniaeth Canolbarth Affrica',
    'cgName': 'Gweriniaeth y Congo',
    'chName': 'Y Swistir',
    'ciName': 'Arfordir Ifori',
    'clName': 'Tsile',
    'cmName': 'Camerŵn',
    'cnName': 'Tsieina',
    'coName': 'Colombia',
    'crName': 'Costa Rica',
    'cuName': 'Ciwba',
    'cvName': 'Cabo Verde',
    'cyName': 'Cyprus',
    'czName': 'Y Weriniaeth Tsiec',
    'deName': 'Yr Almaen',
    'djName': 'Jibwti',
    'dkName': 'Denmarc',
    'dmName': 'Dominica',
    'doName': 'Gweriniaeth Dominica',
    'dzName': 'Algeria',
    'ecName': 'Ecwador',
    'eeName': 'Estonia',
    'egName': 'Yr Aifft',
    'erName': 'Eritrea',
    'esName': 'Sbaen',
    'etName': 'Ethiopia',
    'fiName': 'Y Ffindir',
    'fjName': 'Ffiji',
    'fmName': 'Micronesia',
    'frName': 'Ffrainc',
    'gaName': 'Gabon',
    'gbName': 'Y Deyrnas Unedig',
    'gdName': 'Grenada',
    'geName': 'Georgia',
    'ghName': 'Ghana',
    'gmName': 'Y Gambia',
    'gnName': 'Gini',
    'gqName': 'Gini Cyhydeddol',
    'grName': 'Gwlad Groeg',
    'gtName': 'Gwatemala',
    'gwName': 'Gini Bisaw',
    'gyName': 'Gaiana',
    'hnName': 'Hondwras',
    'hrName': 'Croatia',
    'htName': 'Haiti',
    'huName': 'Hwngari',
    'idName': 'Indonesia',
    'ieName': 'Iwerddon',
    'ilName': 'Israel',
    'inName': 'India',
    'iqName': 'Irac',
    'irName': 'Iran',
    'isName': 'Gwlad yr Iâ',
    'itName': 'Yr Eidal',
    'jmName': 'Jamaica',
    'joName': 'Gwlad Iorddonen',
    'jpName': 'Japan',
    'keName': 'Cenia',
    'kgName': 'Cirgistan',
    'khName': 'Cambodia',
    'kiName': 'Ciribati',
    'kmName': 'Y Comoros',
    'knName': 'Sant Kitts-Nevis',
    'kpName': 'Gogledd Corea',
    'krName': 'De Corea',
    'kwName': 'Coweit',
    'kzName': 'Casachstan',
    'laName': 'Laos',
    'lbName': 'Libanus',
    'lcName': 'Sant Lwsia',
    'liName': 'Liechtenstein',
    'lkName': 'Sri Lanka',
    'lrName': 'Liberia',
    'lsName': 'Lesotho',
    'ltName': 'Lithwania',
    'luName': 'Lwcsembwrg',
    'lvName': 'Latfia',
    'lyName': 'Libia',
    'maName': 'Moroco',
    'mcName': 'Monaco',
    'mdName': 'Moldofa',
    'meName': 'Montenegro',
    'mgName': 'Madagascar',
    'mhName': 'Ynysoedd Marshall',
    'mkName': 'Gogledd Macedonia',
    'mlName': 'Mali',
    'mmName': 'Myanmar',
    'mnName': 'Mongolia',
    'mrName': 'Mawritania',
    'mtName': 'Malta',
    'muName': 'Mawrisiws',
    'mvName': 'Maldives',
    'mwName': 'Malawi',
    'mxName': 'Mecsico',
    'myName': 'Maleisia',
    'mzName': 'Mosambic',
    'naName': 'Namibia',
    'neName': 'Niger',
    'ngName': 'Nigeria',
    'niName': 'Nicaragwa',
    'nlName': 'Yr Iseldiroedd',
    'noName': 'Norwy',
    'npName': 'Nepal',
    'nrName': 'Nawrw',
    'nzName': 'Seland Newydd',
    'omName': 'Oman',
    'paName': 'Panama',
    'peName': 'Periw',
    'pgName': 'Papua Gini Newydd',
    'phName': 'Y Philipinau',
    'pkName': 'Pacistan',
    'plName': 'Gwlad Pwyl',
    'ptName': 'Portiwgal',
    'pwName': 'Palaw',
    'pyName': 'Paragwâi',
    'qaName': 'Qatar',
    'roName': 'Rwmania',
    'rsName': 'Serbia',
    'ruName': 'Rwsia',
    'rwName': 'Rwanda',
    'saName': 'Sawdi Arabia',
    'sbName': 'Ynysoedd Solomon',
    'scName': 'Seychelles',
    'sdName': 'Swdan',
    'seName': 'Sweden',
    'sgName': 'Singapôr',
    'siName': 'Slofenia',
    'skName': 'Slofacia',
    'slName': 'Sierra Leone',
    'smName': 'San Marino',
    'snName': 'Senegal',
    'soName': 'Somalia',
    'srName': 'Swrinam',
    'ssName': 'De Swdan',
    'stName': 'São Tomé a Príncipe',
    'svName': 'El Salfador',
    'syName': 'Syria',
    'szName': 'Eswatini',
    'tdName': 'Tsiad',
    'tgName': 'Togo',
    'thName': 'Gwlad Tai',
    'tjName': 'Tajicistan',
    'tlName': 'Dwyrain Timor',
    'tmName': 'Tyrcmenistan',
    'tnName': 'Tiwnisia',
    'toName': 'Tonga',
    'trName': 'Twrci',
    'ttName': 'Trinidad a Thobago',
    'tvName': 'Twfalw',
    'tzName': 'Tansanïa',
    'uaName': 'Yr Wcráin',
    'ugName': 'Wganda',
    'usName': 'Unol Daleithiau',
    'uyName': 'Wrwgwái',
    'uzName': 'Wsbecistan',
    'vcName': 'Saint Vincent a\'r Grenadines',
    'veName': 'Feneswela',
    'vnName': 'Fietnam',
    'vuName': 'Fanwatw',
    'wsName': 'Samoa',
    'yeName': 'Iemen',
    'zaName': 'De Affrica',
    'zmName': 'Sambia',
    'zwName': 'Simbabwe',
  };

  static const _ga = {
    'adName': 'Andóra',
    'aeName': 'Aontas na nÉimíríochtaí Arabacha',
    'afName': 'An Afganastáin',
    'agName': 'Antigua agus Barbúda',
    'alName': 'An Albáin',
    'amName': 'An Airméin',
    'aoName': 'Angóla',
    'arName': 'An Airgintín',
    'atName': 'An Ostair',
    'auName': 'An Astráil',
    'azName': 'An Asarbaiseáin',
    'baName': 'An Bhoisnia agus an Heirseagaivéin',
    'bbName': 'Barbadós',
    'bdName': 'An Bhanglaidéis',
    'beName': 'An Bheilg',
    'bfName': 'Buircíne Fasó',
    'bgName': 'An Bhulgáir',
    'bhName': 'Bairéin',
    'biName': 'An Bhurúin',
    'bjName': 'Beinin',
    'bnName': 'Brúiné',
    'boName': 'An Bholaiv',
    'brName': 'An Bhrasaíl',
    'bsName': 'Na Bahámaí',
    'btName': 'Bhútáin',
    'bwName': 'Bhotsuáin',
    'byName': 'An Bhealarúis',
    'bzName': 'An Bheilís',
    'caName': 'Ceanada',
    'cdName': 'Chongó (Poblacht Dhaonlathach an)',
    'cfName': 'Poblacht na hAfraice Láir',
    'cgName': 'Chongó (Poblacht an)',
    'chName': 'An Eilvéis',
    'ciName': 'An Cósta Eabhair',
    'clName': 'An tSile',
    'cmName': 'Camarún',
    'cnName': 'An tSín',
    'coName': 'An Cholóim',
    'crName': 'Cósta Ríce',
    'cuName': 'Cúba',
    'cvName': 'Rinn Verde',
    'cyName': 'An Chipir',
    'czName': 'Poblacht na Seice',
    'deName': 'An Ghearmáin',
    'djName': 'Djibouti',
    'dkName': 'An Danmhairg',
    'dmName': 'Doiminice',
    'doName': 'An Phoblacht Dhoiminiceach',
    'dzName': 'An Ailgéir',
    'ecName': 'Eacuadór',
    'eeName': 'An Eastóin',
    'egName': 'An Éigipt',
    'erName': 'An Eiritré',
    'esName': 'An Spáinn',
    'etName': 'An Aetóip',
    'fiName': 'An Fhionlainn',
    'fjName': 'Fidsí',
    'fmName': 'An Mhicrinéis',
    'frName': 'An Fhrainc',
    'gaName': 'An Ghabúin',
    'gbName': 'An Ríocht Aontaithe',
    'gdName': 'Greanáda',
    'geName': 'An tSeoirsia',
    'ghName': 'Gána',
    'gmName': 'An Ghaimbia',
    'gnName': 'An Guine',
    'gqName': 'An Ghuine Mheánchriosach',
    'grName': 'An Ghréig',
    'gtName': 'Guatamala',
    'gwName': 'Guine Bissau',
    'gyName': 'An Ghuáin',
    'hnName': 'Hondúras',
    'hrName': 'An Chróit',
    'htName': 'Háití',
    'huName': 'An Ungáir',
    'idName': 'An Indinéis',
    'ieName': 'Éire',
    'ilName': 'Iosrael',
    'inName': 'An India',
    'iqName': 'Iaráic',
    'irName': 'An Iaráin',
    'isName': 'An Íoslainn',
    'itName': 'An Iodáil',
    'jmName': 'Iamáice',
    'joName': 'An Iordáin',
    'jpName': 'An tSeapáin',
    'keName': 'An Chéinia',
    'kgName': 'An Chirgeastáin',
    'khName': 'An Chambóid',
    'kiName': 'Cireabaití',
    'kmName': 'Oileáin Chomóra',
    'knName': 'San Críostóir-Nimheas',
    'kpName': 'An Chóiré Thuaidh',
    'krName': 'An Chóiré Theas',
    'kwName': 'Cuáit',
    'kzName': 'An Chasacstáin',
    'laName': 'Laos',
    'lbName': 'An Liobáin',
    'lcName': 'Saint Lucia',
    'liName': 'Lichtinstéin',
    'lkName': 'Srí Lanca',
    'lrName': 'An Libéir',
    'lsName': 'Leosóta',
    'ltName': 'An Liotuáin',
    'luName': 'Lucsamburg',
    'lvName': 'An Laitvia',
    'lyName': 'An Libia',
    'maName': 'Maracó',
    'mcName': 'Monacó',
    'mdName': 'An Mholdóiv',
    'meName': 'Montainéagró',
    'mgName': 'Madagascar',
    'mhName': 'Oileáin Marshall',
    'mkName': 'Poblacht na Macadóine',
    'mlName': 'Mailí',
    'mmName': 'Maenmar',
    'mnName': 'An Mhongóil',
    'mrName': 'An Mháratáin',
    'mtName': 'Málta',
    'muName': 'Oileán Mhuirís',
    'mvName': 'Oileáin Mhaildíve',
    'mwName': 'An Mhaláiv',
    'mxName': 'Meicsiceo',
    'myName': 'An Mhalaeisia',
    'mzName': 'Mósaimbíc',
    'naName': 'An Namaib',
    'neName': 'An Nígir',
    'ngName': 'An Nigéir',
    'niName': 'Nicearagua',
    'nlName': 'An Ísiltír',
    'noName': 'An Iorua',
    'npName': 'Neipeal',
    'nrName': 'Nárú',
    'nzName': 'An Nua-Shéalainn',
    'omName': 'Óman',
    'paName': 'Panama',
    'peName': 'Peiriú',
    'pgName': 'Nua-Ghuine Phapua',
    'phName': 'Na hOileáin Fhilipíneacha',
    'pkName': 'An Phacastáin',
    'plName': 'An Pholainn',
    'ptName': 'An Phortaingéil',
    'pwName': 'Oileáin Palau',
    'pyName': 'Paragua',
    'qaName': 'Catar',
    'roName': 'An Rómáin',
    'rsName': 'An tSeirbia',
    'ruName': 'An Rúis',
    'rwName': 'Ruanda',
    'saName': 'An Araib Shádach',
    'sbName': 'Oileáin Sholamón',
    'scName': 'Na Séiséil',
    'sdName': 'An tSúdáin',
    'seName': 'An tSualainn',
    'sgName': 'Singeapór',
    'siName': 'An tSlóivéin',
    'skName': 'An tSlóvaic',
    'slName': 'Siarra Leon',
    'smName': 'San Mairíne',
    'snName': 'An tSeineagáil',
    'soName': 'An tSomáil',
    'srName': 'Suranam',
    'ssName': 'An tSúdáin Theas',
    'stName': 'São Tomé agus Príncipe',
    'svName': 'An tSalvadóir',
    'syName': 'An tSiria',
    'szName': 'An tSuasalainn',
    'tdName': 'Sead',
    'tgName': 'Tóga',
    'thName': 'An Téalainn',
    'tjName': 'An Táidsíceastáin',
    'tlName': 'Tíomór-Leste',
    'tmName': 'An Tuircméanastáin',
    'tnName': 'An Túinéis',
    'toName': 'Tonga',
    'trName': 'An Tuirc',
    'ttName': 'Oileán na Tríonóide agus Tobága',
    'tvName': 'Túvalú',
    'tzName': 'An Tansáin',
    'uaName': 'An Úcráin',
    'ugName': 'Uganda',
    'usName': 'Stáit Aontaithe Mheiriceá',
    'uyName': 'Uragua',
    'uzName': 'An Úisbéiceastáin',
    'vcName': 'San Uinseann agus na Greanáidíní',
    'veName': 'Veiniséala',
    'vnName': 'Vítneam',
    'vuName': 'Vanuatú',
    'wsName': 'Samó',
    'yeName': 'Éimin',
    'zaName': 'An Afraic Theas',
    'zmName': 'An tSaimbia',
    'zwName': 'An tSiombáib',
  };

  static final _locales = {
    'en': _en,
    'by': _by,
    'cy': _cy,
    'ga': _ga,
  };
}

class _$CountryLocalizationsDelegate {
  static final _supportedLocales = {
    Locale('en'),
    Locale('by'),
    Locale('cy'),
    Locale('ga'),
  };
}
