name: publish_codecov
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Generate + Publish Code Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/set_up_flutter
      - name: Generate coverage_report_test.dart
        run: flutter pub run dart_code_coverage:generate_dart_file -r ".*\.g\.dart","localizations.dart"
      - name: Generate coverage/lcov.info
        run: flutter test --coverage --exclude-tags app_store_screenshots
      - name: Clean up coverage/lcov.info
        run: flutter pub run dart_code_coverage:edit_lcov -r ".*\.g\.dart","localizations.dart","app_icon.dart"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
