name: publish_codecov
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Generate + Publish Code Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Install packages
        run: flutter pub get
      - name: Generate coverage_report_test.dart
        run: flutter pub run dart_code_coverage:generate_dart_file -r ".*\.g\.dart","localizations.dart","generated_plugin_registrant.dart"
      - name: Generate coverage/lcov.info
        run: flutter test --coverage
      - name: Clean up coverage/lcov.info
        run: flutter pub run dart_code_coverage:edit_lcov -r ".*\.g\.dart","localizations.dart"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
